# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"load_cleaned_data": "10-load-data.ipynb",
         "get_standard_split": "10-load-data.ipynb",
         "make_model_pipeline": "20-ml-experiments.ipynb"}

modules = ["load_data.py",
           "modeling.py"]

doc_url = "https://csbell-vu.github.io/sklearn_demo/"

git_url = "https://github.com/csbell-vu/sklearn_demo/tree/main/"

def custom_doc_links(name): return None
