# AUTOGENERATED! DO NOT EDIT! File to edit: 10-load-data.ipynb (unless otherwise specified).

__all__ = ['load_cleaned_data', 'get_standard_split']

# Cell
import pandas as pd
from sklearn.model_selection import train_test_split

# Cell
def load_cleaned_data():

    # load the data
    penguins = pd.read_csv('https://raw.githubusercontent.com/allisonhorst/palmerpenguins/master/inst/extdata/penguins.csv')

    # clean the data
    penguins = penguins.dropna(subset=['sex'])

    return penguins

# Cell
def get_standard_split(df_in, class_col, random_state=1234, train_pct=0.8):

    X_train, X_test, y_train, y_test = train_test_split(df_in.drop(columns=class_col), df_in[class_col],
                                                        test_size=0.25, random_state=random_state,
                                                        stratify=df_in[class_col])

    return X_train, X_test, y_train, y_test