# AUTOGENERATED! DO NOT EDIT! File to edit: 20-ml-experiments.ipynb (unless otherwise specified).

__all__ = ['make_model_pipeline']

# Cell
def make_model_pipeline(mdl):

    #individual pipelines for differing datatypes
    cat_pipeline = Pipeline(steps=[('cat_impute', SimpleImputer(missing_values=np.nan, strategy='most_frequent')),
                               ('onehot_cat', OneHotEncoder(drop='if_binary'))])
    num_pipeline = Pipeline(steps=[('impute_num', SimpleImputer(missing_values=np.nan, strategy='mean')),
                               ('scale_num', StandardScaler())])

    #establish preprocessing pipeline by columns
    preproc = ColumnTransformer([('cat_pipe', cat_pipeline, make_column_selector(dtype_include=object)),
                             ('num_pipe', num_pipeline, make_column_selector(dtype_include=np.number))],
                             remainder='passthrough')

    #make pipeline
    pipe_out = Pipeline(steps=[('preproc', preproc),
                       ('mdl', mdl)])

    return pipe_out